<a href="https://colab.research.google.com/github/Aniket-Singh25cp/aiml-bootcamp-2026/blob/main/bootcamp_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

subjects = ["Python", "Math", "AI", "Data"]
#print the first value of list
print(subjects)
print(subjects[0])
print(subjects[-1])

['Python', 'Math', 'AI', 'Data']
Python
Data


In [2]:
students = [
    {
        "name": "Raju",
        "course": "Btech",
        "city": "mathura",
        "college": "gLa",
        "grade": "A"
    },
    {
        "name": "Kaju",
        "course": "mtech",
        "city": "noida",
        "college": "glbajaj",
        "grade": "A1"
    },
    {
        "name": "Ram",
        "course": "bba",
        "city": "mathura",
        "college": "sanskriti",
        "grade": "A2"
    },
    {
        "name": "Shyam",
        "course": "bca",
        "city": "mathura",
        "college": "gLa",
        "grade": "A3"
    }
]
for student in students:
    if student.get("grade") > "A":
        print(student)
marks = 72

if marks>=40:
  print("Pass")
else:
  print("Fail")

{'name': 'Kaju', 'course': 'mtech', 'city': 'noida', 'college': 'glbajaj', 'grade': 'A1'}
{'name': 'Ram', 'course': 'bba', 'city': 'mathura', 'college': 'sanskriti', 'grade': 'A2'}
{'name': 'Shyam', 'course': 'bca', 'city': 'mathura', 'college': 'gLa', 'grade': 'A3'}
Pass


In [3]:

marks=72
if marks>40 and marks<79:
  print("pass")
elif marks>=80:
  print("dis")
else:
  print("fail")

pass


In [4]:

marks=72
if marks%2==0:
  print("even")
else:
  print("odd")

even


In [5]:

age=int(input())
if age<13:
  print("child")
elif age>13 and age<19:
  print("teenager")
else:
  print("Old")

25
Old


In [6]:
student = [
    {
        "name": "arving",
        "lab": True,
        "age": 17,
        "marks": 53
    },
    {
        "name": "radha",
        "lab": False,
        "age": 25,
        "marks": 531
    },
    {
        "name": "harsh",
        "lab": True,
        "age": 23,
        "marks": 21
    }
]

for i in student:
    if i["lab"] == False:
        result = "Lab Assign Not Submitted"
    elif i["marks"] >= 90:
        result = "Distinction"
    elif i["marks"] >= 75:
        result = "Pass"
    elif i["marks"] >= 40:
        result = "Improve"
    else:
        result = "Fail"

In [7]:
#Function
def grade(marks):
  if marks<40:
    return "fail"
  else:
    return "Pass"
mark=int(input())
print(grade(mark))

25
fail


In [8]:
#numpy starts here.
import numpy as np
marks = np.array([78,91,55,72,40,88])
marks_2d=marks.reshape(2,3)
print(marks_2d.max())
print(marks_2d)

91
[[78 91 55]
 [72 40 88]]


In [9]:
import pandas as pd
df= pd.read_csv("/content/session4_dummy_students_data.csv.xls")
print(df)

    student_id    name  age     city  math  science  english  \
0          101   Aarav   16   Mumbai    78       84       69   
1          102    Diya   16    Delhi    91       88       94   
2          103   Kabir   17  Mathura    55       61       58   
3          104   Meera   16    Noida    72       79       81   
4          105   Rohan   17   Mumbai    40       52       47   
5          106    Sara   16    Delhi    88       93       90   
6          107  Ishaan   17  Mathura    64       70       66   
7          108  Ananya   16    Noida    95       92       89   
8          109  Vivaan   17   Mumbai    48       57       51   
9          110    Tara   16    Delhi    83       76       85   
10         111   Arjun   17  Mathura    67       63       72   
11         112   Nisha   16    Noida    74       81       79   
12         113     Dev   17   Mumbai    35       45       42   
13         114   Priya   16    Delhi    89       86       91   
14         115   Kunal   17  Mathura    

In [11]:
#convert math score column to numpy array

import numpy as np
math_score= df["math"].to_numpy()
print(math_score)
print(type(math_score))
print(math_score.mean())

[78 91 55 72 40 88 64 95 48 83 67 74 35 89 58 92 61 80 43 77]
<class 'numpy.ndarray'>
69.5


In [12]:
#for science score column
science_score= df["science"].to_numpy
print(science_score)

<bound method IndexOpsMixin.to_numpy of 0     84
1     88
2     61
3     79
4     52
5     93
6     70
7     92
8     57
9     76
10    63
11    81
12    45
13    86
14    54
15    90
16    69
17    85
18    49
19    73
Name: science, dtype: int64>


In [13]:
#calculate average marks across all subjects
science_score = df["science"].to_numpy()
math_score = df["math"].to_numpy()
english_score = df["english"].to_numpy()

avg = df[["science", "math", "english"]].mean(axis=1)


top_names = df[avg > 85]["name"]

low_attendance_names = df[df["attendance_percent"] < 75]["name"]

mathura_names = df[df["city"] == "Mathura"]["name"]
print(top_names)
print(low_attendance_names)
print(mathura_names)

1       Diya
5       Sara
7     Ananya
13     Priya
15      Riya
Name: name, dtype: object
4      Rohan
8     Vivaan
12       Dev
18      Yash
Name: name, dtype: object
2      Kabir
6     Ishaan
10     Arjun
14     Kunal
18      Yash
Name: name, dtype: object


In [14]:
df["average"] = (df["math"] + df["science"] + df["english"]) / 3

df["result"] = "Fail"
df.loc[df["average"] >= 40, "result"] = "Pass"

print("Class Average:", df["average"].mean())

print("Highest Average:", df["average"].max())
print("Lowest Average:", df["average"].min())

top_students = df[df["average"] == df["average"].max()]
print("Top Student:")
print(top_students["name"])

print("Attendance Below 75:")
print(df[df["attendance_percent"] < 75]["name"])

print("Assignments Below 6:")
print(df[df["assignments_submitted"] < 6]["name"])

Class Average: 71.35000000000001
Highest Average: 92.66666666666667
Lowest Average: 40.666666666666664
Top Student:
15    Riya
Name: name, dtype: object
Attendance Below 75:
4      Rohan
8     Vivaan
12       Dev
18      Yash
Name: name, dtype: object
Assignments Below 6:
4     Rohan
12      Dev
18     Yash
Name: name, dtype: object
